workflows:
  flutter-app:
    name: Tleukzh iOS & Android
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Build Android
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - arcnosixta@gmail.com
